/**
 * @fileOverview Cryptography utility functions.
 */

import { AFC } from './imports';
import * as crypto from 'crypto';

// Default entropy size.
const ENTROPY_SIZE = 32;

/**
 * Returns API request authentication signature.
 *
 * @param {accessfile-core.HDKey} keyPair - Derived ECC key pair used to sign/verify.
 * @param {object} data - Request data to be dispatached to API.
 */
export const getRequestSignature = (keyPair, data) => {
    const { privateKey, publicKey } = keyPair;
    const { sig, hash } = AFC.getSignature(privateKey, data);

    return {
        hash: hash.toString('hex'),
        publicKey: publicKey.toString('hex'),
        signature: sig.toString('hex'),
    };
};

/**
 * Returns randomness, i.e. entropy, derived from a PRNG.
 *
 * @param {number} size - A number indicating the number of bytes to generate.
 * @return {Buffer} Buffer containing generated bytes.
 */
export const getRandomString = (size) => {
    return AFC.getEntropy(size || ENTROPY_SIZE).toString('hex');
}
