//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keane.CH.Framework.Services.Logging.Implementation.EntLib.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XmlElementConstants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XmlElementConstants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Keane.CH.Framework.Services.Logging.Implementation.EntLib.Resources.XmlElementCon" +
                            "stants", typeof(XmlElementConstants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE_TIME_STAMP.
        /// </summary>
        internal static string DateTimeStamp {
            get {
                return ResourceManager.GetString("DateTimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR_CATEGORY.
        /// </summary>
        internal static string ErrorCategory {
            get {
                return ResourceManager.GetString("ErrorCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR_CODE.
        /// </summary>
        internal static string ErrorCode {
            get {
                return ResourceManager.GetString("ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR_MESSAGE.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR_RESPONSE.
        /// </summary>
        internal static string ErrorResponse {
            get {
                return ResourceManager.GetString("ErrorResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR_SEVERITY.
        /// </summary>
        internal static string ErrorSeverity {
            get {
                return ResourceManager.GetString("ErrorSeverity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExecutionContext.
        /// </summary>
        internal static string ExecutionContext {
            get {
                return ResourceManager.GetString("ExecutionContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly.
        /// </summary>
        internal static string ExecutionContextAssembly {
            get {
                return ResourceManager.GetString("ExecutionContextAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        internal static string ExecutionContextMethodName {
            get {
                return ResourceManager.GetString("ExecutionContextMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MethodParameters.
        /// </summary>
        internal static string ExecutionContextMethodParameters {
            get {
                return ResourceManager.GetString("ExecutionContextMethodParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MethodResult.
        /// </summary>
        internal static string ExecutionContextMethodResult {
            get {
                return ResourceManager.GetString("ExecutionContextMethodResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        internal static string ExecutionContextParameter {
            get {
                return ResourceManager.GetString("ExecutionContextParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParameterList.
        /// </summary>
        internal static string ExecutionContextParameterList {
            get {
                return ResourceManager.GetString("ExecutionContextParameterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ExecutionContextParameterName {
            get {
                return ResourceManager.GetString("ExecutionContextParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string ExecutionContextParameterValue {
            get {
                return ResourceManager.GetString("ExecutionContextParameterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemLayer.
        /// </summary>
        internal static string ExecutionContextSystemLayer {
            get {
                return ResourceManager.GetString("ExecutionContextSystemLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ExecutionContextTypeName {
            get {
                return ResourceManager.GetString("ExecutionContextTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fault.
        /// </summary>
        internal static string Fault {
            get {
                return ResourceManager.GetString("Fault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InnerException.
        /// </summary>
        internal static string FaultInnerException {
            get {
                return ResourceManager.GetString("FaultInnerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string FaultMessage {
            get {
                return ResourceManager.GetString("FaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string FaultSource {
            get {
                return ResourceManager.GetString("FaultSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StackTrace.
        /// </summary>
        internal static string FaultStackTrace {
            get {
                return ResourceManager.GetString("FaultStackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TargetSite.
        /// </summary>
        internal static string FaultTargetSite {
            get {
                return ResourceManager.GetString("FaultTargetSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogMessage.
        /// </summary>
        internal static string LogMessage {
            get {
                return ResourceManager.GetString("LogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string LogMessageApplicationName {
            get {
                return ResourceManager.GetString("LogMessageApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string LogMessageCategory {
            get {
                return ResourceManager.GetString("LogMessageCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContextData.
        /// </summary>
        internal static string LogMessageContextData {
            get {
                return ResourceManager.GetString("LogMessageContextData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EventType.
        /// </summary>
        internal static string LogMessageEventType {
            get {
                return ResourceManager.GetString("LogMessageEventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExecutionDetails.
        /// </summary>
        internal static string LogMessageExecutionDetails {
            get {
                return ResourceManager.GetString("LogMessageExecutionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string LogMessageId {
            get {
                return ResourceManager.GetString("LogMessageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string LogMessageMessage {
            get {
                return ResourceManager.GetString("LogMessageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageContext.
        /// </summary>
        internal static string LogMessageMessageContext {
            get {
                return ResourceManager.GetString("LogMessageMessageContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string LogMessagePriority {
            get {
                return ResourceManager.GetString("LogMessagePriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeStamp.
        /// </summary>
        internal static string LogMessageTimeStamp {
            get {
                return ResourceManager.GetString("LogMessageTimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessContext.
        /// </summary>
        internal static string ProcessContext {
            get {
                return ResourceManager.GetString("ProcessContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MachineIp.
        /// </summary>
        internal static string ProcessContextMachineIp {
            get {
                return ResourceManager.GetString("ProcessContextMachineIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine.
        /// </summary>
        internal static string ProcessContextMachineName {
            get {
                return ResourceManager.GetString("ProcessContextMachineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSVersion.
        /// </summary>
        internal static string ProcessContextMachineOSVersion {
            get {
                return ResourceManager.GetString("ProcessContextMachineOSVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThreadId.
        /// </summary>
        internal static string ProcessContextThreadId {
            get {
                return ResourceManager.GetString("ProcessContextThreadId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThreadName.
        /// </summary>
        internal static string ProcessContextThreadName {
            get {
                return ResourceManager.GetString("ProcessContextThreadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserDomain.
        /// </summary>
        internal static string ProcessContextUserDomainName {
            get {
                return ResourceManager.GetString("ProcessContextUserDomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string ProcessContextUserName {
            get {
                return ResourceManager.GetString("ProcessContextUserName", resourceCulture);
            }
        }
    }
}
