#!/usr/bin/env bash

# ###############################################################
# PATH
# ###############################################################

# Set path -> here.
export MPCTL="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Utility version.
export MPCTL_VERSION="1.0.0"

# ###############################################################
# COMMANDS
# ###############################################################

# Infra docker.
alias mpctl-dkr-build-image='source $MPCTL/cmds/dkr/build_image.sh'
alias mpctl-dkr-build-images='source $MPCTL/cmds/dkr/build_images.sh'
alias mpctl-dkr-e2e-down='source $MPCTL/cmds/dkr/ctl.sh             target=e2e action=down'
alias mpctl-dkr-e2e-run='source $MPCTL/cmds/dkr/ctl.sh              target=e2e action=run'
alias mpctl-dkr-e2e-up='source $MPCTL/cmds/dkr/ctl.sh               target=e2e action=up'
alias mpctl-dkr-net-down='source $MPCTL/cmds/dkr/ctl.sh             target=standard action=down'
alias mpctl-dkr-net-down-genesis='source $MPCTL/cmds/dkr/ctl.sh     target=genesis action=down'
alias mpctl-dkr-net-start='source $MPCTL/cmds/dkr/ctl.sh            target=standard action=start'
alias mpctl-dkr-net-start-genesis='source $MPCTL/cmds/dkr/ctl.sh    target=genesis action=start'
alias mpctl-dkr-net-stop='source $MPCTL/cmds/dkr/ctl.sh             target=standard action=stop'
alias mpctl-dkr-net-stop-genesis='source $MPCTL/cmds/dkr/ctl.sh     target=genesis action=stop'
alias mpctl-dkr-net-up='source $MPCTL/cmds/dkr/ctl.sh               target=standard action=up'
alias mpctl-dkr-net-up-genesis='source $MPCTL/cmds/dkr/ctl.sh       target=genesis action=up'
alias mpctl-dkr-init-db-for-genesis='source $MPCTL/cmds/dkr/init_db_for_genesis.sh'
alias mpctl-dkr-node-start='source $MPCTL/cmds/dkr/node_start.sh'
alias mpctl-dkr-node-start-genesis='source $MPCTL/cmds/dkr/node_start.sh binary=genesis'
alias mpctl-dkr-node-stop='source $MPCTL/cmds/dkr/node_stop.sh'
alias mpctl-dkr-node-stop-genesis='source $MPCTL/cmds/dkr/node_stop.sh binary=genesis'
alias mpctl-dkr-node-view-logs='source $MPCTL/cmds/dkr/node_view_logs.sh'
alias mpctl-dkr-node-view-logs-genesis='source $MPCTL/cmds/dkr/node_view_logs.sh binary=genesis'
alias mpctl-dkr-services-down='source $MPCTL/cmds/dkr/ctl.sh        target=services action=down'
alias mpctl-dkr-services-reset='source $MPCTL/cmds/dkr/ctl.sh       target=services action=reset'
alias mpctl-dkr-services-up='source $MPCTL/cmds/dkr/ctl.sh          target=services action=up'
alias mpctl-dkr-system-down='source $MPCTL/cmds/dkr/ctl.sh          target=system action=down'
alias mpctl-dkr-system-reset='source $MPCTL/cmds/dkr/ctl.sh         target=system action=reset'
alias mpctl-dkr-system-up='source $MPCTL/cmds/dkr/ctl.sh            target=system action=up'

# Infra local (i.e. baremetal).
alias mpctl-local-compile-binaries='source $MPCTL/cmds/local/compile_binaries.sh'
alias mpctl-local-e2e-run='source $MPCTL/cmds/local/e2e_run.sh'
alias mpctl-local-net-reset='mpctl-local-net-teardown && mpctl-local-net-setup && mpctl-local-net-start'
alias mpctl-local-net-reset-genesis='mpctl-local-net-teardown && mpctl-local-net-setup && mpctl-local-net-start-genesis'
alias mpctl-local-net-setup='source $MPCTL/cmds/local/net_setup.sh'
alias mpctl-local-net-start='source $MPCTL/cmds/local/net_start.sh'
alias mpctl-local-net-start-genesis='source $MPCTL/cmds/local/net_start_genesis.sh'
alias mpctl-local-net-teardown='source $MPCTL/cmds/local/net_teardown.sh'
alias mpctl-local-net-update-binaries='source $MPCTL/cmds/local/net_update_binaries.sh'
alias mpctl-local-node-activate-env='source $MPCTL/cmds/local/node_activate_env.sh'
alias mpctl-local-node-start='source $MPCTL/cmds/local/node_start.sh'
alias mpctl-local-node-start-genesis='source $MPCTL/cmds/local/node_start_genesis.sh'
alias mpctl-local-node-update-binaries='source $MPCTL/cmds/local/node_update_binaries.sh'
alias mpctl-local-node-view-env='source $MPCTL/cmds/local/node_view_env.sh'
alias mpctl-local-node-view-logs='source $MPCTL/cmds/local/node_view_logs.sh'

# Developer helpers.
alias mpctl-dev-apply-linter='source $MPCTL/jobs/dev/apply_linter.sh'
alias mpctl-dev-run-tests='source $MPCTL/jobs/dev/run_tests.sh'
alias mpctl-ls='source $MPCTL/jobs/dev/view_commands.sh'

# Jobs.
alias mpctl-job-aws-sm-rotate-keys='source $MPCTL/jobs/services/aws_sm_rotate.sh'
alias mpctl-job-write-iris-deletions-file='source $MPCTL/jobs/testing/write_iris_serial_ids_for_deletion.sh'
alias mpctl-job-write-node-config-files='source $MPCTL/jobs/testing/write_node_config_files.sh'
alias mpctl-job-write-plain-text-iris-file='source $MPCTL/jobs/testing/write_plain_text_iris_file.sh'

# Jobs: pgres.
alias mpctl-job-pgres-dump='source $MPCTL/jobs/services/pgres_dump.sh'
alias mpctl-job-pgres-init-from-plain-text-iris-file='source $MPCTL/jobs/testing/init_db_from_plain_text_iris_file.sh'
alias mpctl-job-pgres-restore='source $MPCTL/jobs/services/pgres_restore.sh'
alias mpctl-job-pgres-truncate-all='source $MPCTL/jobs/services/pgres_truncate.sh group=all'
alias mpctl-job-pgres-truncate-cpu-tables='source $MPCTL/jobs/services/pgres_truncate.sh group=cpu'
alias mpctl-job-pgres-truncate-gpu-tables='source $MPCTL/jobs/services/pgres_truncate.sh group=gpu'
