/**
 * @fileOverview dB schema for an order generated by trading engine.
 */

import { default as mongoose } from 'mongoose';
import { CONSTANTS } from '../../../utils/imports';

// Destructure enums.
const { trading : {
    BookSideEnum,
    OrderFillPreferenceEnum,
    OrderStateEnum,
    OrderTypeEnum
} } = CONSTANTS;

/**
 * dB schema for an order's options.
 */
const OrderOptionsSchema = new mongoose.Schema({
    fillPreference: {
        type: String,
        required: false,
        enum: Object.keys(OrderFillPreferenceEnum)
    },

    fillLowerBound: {
        type: String,
        required: false,
    },

    merchantID: {
        type: String,
        required: false,
    },

    otcOrderID: {
        type: String,
        required: false,
    }
}, {
    _id: false,
    collection: 'trading-order-option'
});

/**
 * dB schema for an order.
 */
const OrderSchema = new mongoose.Schema({
    addressOfBaseAsset: {
        type: String,
        required: true,
    },

    addressOfQuoteAsset: {
        type: String,
        required: true,
    },

    assetPair: {
        type: String,
        required: true,
    },

    customerID: {
        type: String,
        required: true,
    },

    customerReferenceID: {
        type: String,
        required: false,
    },

    exchangeID: {
        type: String,
        required: true,
    },

    exchangeSymbol: {
        type: String,
        required: true,
    },

    options: {
        type: OrderOptionsSchema,
        required: true,
    },

    orderID: {
        index: true,
        unique: true,
        type: String,
        required: true,
    },

    price: {
        type: String,
        required: false,
    },

    quantity: {
        type: String,
        required: true,
    },

    quantityFilled: {
        type: String,
        required: true,
    },

    quoteID: {
        type: String,
        required: true,
    },

    quoteTimestamp: {
        type: Date,
        required: true,
    },

    side: {
        type: String,
        required: true,
        enum: Object.keys(BookSideEnum),
    },

    state: {
        type: String,
        required: true,
        enum: Object.keys(OrderStateEnum)
    },

    type: {
        type: String,
        required: true,
        enum: Object.keys(OrderTypeEnum),
    }
}, {
    collection: 'trading-order',
    timestamps: { createdAt: 'timestamp', updatedAt: 'timestampUpdate' }
});

export default OrderSchema;
