/**
 * @fileOverview Wraps cryptographic entropy generator.
 */

import * as nacl from 'tweetnacl';

// Default entropy size.
const SIZE_BYTES = 32;

/**
 * Returns randomness, i.e. entropy, derived from a PRNG.
 * @param {UInt} size - Size in bytes of generated entropy.
 * @return {Buffer} Buffer containing generated bytes.
 */
export default (size) => {
    return Buffer.from(nacl.randomBytes(size || SIZE_BYTES));
}
