/**
 * @fileOverview An access file - easier than brain wallets.
 */

import getHash from './hashing/blake2b';
import { decrypt, encrypt } from './encryption/index';
import getEntropy from './entropy/index';
import deriveKeyPair from './keys/bip44';
import { getMnemonic, getSeed } from './keys/bip39';
import { ed25519 } from './ecc/index';

// Library version.
export const NAME = 'accessfile-core';

// Library provider.
export const PROVIDER = 'Trinkler Software AG';

// Library version.
export const VERSION = '0.3.0';

/**
 * Decrypts cipher text.
 *
 * @param {Buffer} cipherText - Text to be decrypted.
 * @param {string} password - Password used to encrypt.
 * @param {Buffer} salt - Salt used for key derivation.
 * @param {number} rounds - Number of rounds used for key derivation.
 * @throws IncorrectPasswordError - Raised when the supplied password is incorrect.
 * @return {Promise.<Buffer>} plainText
 */
export { decrypt };

/**
 * Encrypts plain text.
 *
 * @param {Buffer|String} plainText - Text to be encrypted.
 * @param {Buffer|String} password - Password used to encrypt.
 * @param {Buffer|String} salt - Salt used for key derivation.
 * @param {Number} rounds - Number of rounds used for key derivation.
 * @return {Promise.<Buffer>} cipherText
 */
export { encrypt };

/**
 * Returns a key pair derived from a seed over which a derivation path algorithm is applied.
 * @param {Buffer|String} source - Either 32 bytes of entropy, a 24 word mnemonic, or a 64 byte seed.
 * @param {String} coin - Coin symbol, e.g. ETH.
 * @param {Number} account - Account identifier.
 * @param {Bit} chain - 0 = external, 1 = internal.
 * @param {Number} address - Address identifier.
 * @return {keys.HDKey} keyPair - Hierarchically deterministic key pair.
 */
export const getDerivedKeyPair = async (source, coin, account, chain, address) => {
    const seed = await getSeed(source);

    return deriveKeyPair(seed, coin, account, chain, address);
};

/**
 * Returns randomness, i.e. entropy, derived from a PRNG.
 * @param {number} size - A number indicating the number of bytes to generate.
 * @return {Buffer} Buffer containing generated bytes.
 */
export { getEntropy };

/**
 * Returns a blake2b hash of input data.
 * @param {Object} data - Data to be hashed.
 * @return {Buffer} A 32 byte hash of input data.
 */
export { getHash };

/**
 * Returns a key pair for signing / verification purposes.
 * @param {String|Buffer|Array} seed - Randomness with sufficient entropy.
 * @return {Object} A key pair for signing / verification purposes.
 */
export const getKeyPair = ed25519.getKeyPair;

/**
 * Returns a menemonic representation of entropy.
 * @param {Buffer} entropy - A 32 byte buffer generated by a PRNG .
 * @return {String} 24 words.
 */
export { getMnemonic };

/**
 * Returns a 64 byte seed derived from either 32 bytes of entropy or a 24 word mnemonic.
 * @param {String|Buffer} source - Entropy buffer | mnemonic words.
 * @return {Buffer} A 64 byte seed.
 */
export { getSeed };

/**
 * Signs a data structure using an elliptic curve.
 * @param {String|Buffer|Array} pvk - A private key.
 * @param {Object} data - Data to be signed.
 * @param {String} encoding - Required signature encoding, hexadecimal string or byte array.
 * @return {Object} Signature plus data hash.
 */
export const getSignature = (pvk, data) => {
    const hash = getHash(data);
    const sig = ed25519.sign(pvk, hash);

    return { sig, hash };
};

/**
 * Verifies the signature of the hash of the data is verified with the public key.
 * @param {String|Array} key - Either the public or private from a key pair.
 * @param {Object} data - Data previously signed.
 * @param {Array} sig - A digital signature of the message hash in DER array format.
 * @return {Boolean} True if verified, false otherwise.
 */
export const verifySignature = (key, data, sig) => {
    const hash = getHash(data);

    return ed25519.verify(key, hash, sig);
};
