//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keane.CH.Framework.Core.Resources.Xml {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class XmlElementConstants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XmlElementConstants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Keane.CH.Framework.Core.Resources.XmlElementConstants", typeof(XmlElementConstants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATA_CONTRACT.
        /// </summary>
        public static string DataContract {
            get {
                return ResourceManager.GetString("DataContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE_TIME_STAMP.
        /// </summary>
        public static string DateTimeStamp {
            get {
                return ResourceManager.GetString("DateTimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR_CATEGORY.
        /// </summary>
        public static string ErrorCategory {
            get {
                return ResourceManager.GetString("ErrorCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR_CODE.
        /// </summary>
        public static string ErrorCode {
            get {
                return ResourceManager.GetString("ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR_MESSAGE.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR_RESPONSE.
        /// </summary>
        public static string ErrorResponse {
            get {
                return ResourceManager.GetString("ErrorResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR_SEVERITY.
        /// </summary>
        public static string ErrorSeverity {
            get {
                return ResourceManager.GetString("ErrorSeverity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERS_WS.
        /// </summary>
        public static string ErsWsRoot {
            get {
                return ResourceManager.GetString("ErsWsRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExecutionDetails.
        /// </summary>
        public static string ExecutionDetails {
            get {
                return ResourceManager.GetString("ExecutionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationTier.
        /// </summary>
        public static string ExecutionDetailsApplicationTier {
            get {
                return ResourceManager.GetString("ExecutionDetailsApplicationTier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly.
        /// </summary>
        public static string ExecutionDetailsAssemblyName {
            get {
                return ResourceManager.GetString("ExecutionDetailsAssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine.
        /// </summary>
        public static string ExecutionDetailsMachineName {
            get {
                return ResourceManager.GetString("ExecutionDetailsMachineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        public static string ExecutionDetailsMethodName {
            get {
                return ResourceManager.GetString("ExecutionDetailsMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string ExecutionDetailsMethodResult {
            get {
                return ResourceManager.GetString("ExecutionDetailsMethodResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        public static string ExecutionDetailsParameter {
            get {
                return ResourceManager.GetString("ExecutionDetailsParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParameterList.
        /// </summary>
        public static string ExecutionDetailsParameterList {
            get {
                return ResourceManager.GetString("ExecutionDetailsParameterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ExecutionDetailsParameterName {
            get {
                return ResourceManager.GetString("ExecutionDetailsParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string ExecutionDetailsParameterValue {
            get {
                return ResourceManager.GetString("ExecutionDetailsParameterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThreadId.
        /// </summary>
        public static string ExecutionDetailsThreadId {
            get {
                return ResourceManager.GetString("ExecutionDetailsThreadId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string ExecutionDetailsTypeName {
            get {
                return ResourceManager.GetString("ExecutionDetailsTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string ExecutionDetailsUserName {
            get {
                return ResourceManager.GetString("ExecutionDetailsUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FaultInfo.
        /// </summary>
        public static string Fault {
            get {
                return ResourceManager.GetString("Fault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InnerException.
        /// </summary>
        public static string FaultInnerException {
            get {
                return ResourceManager.GetString("FaultInnerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string FaultMessage {
            get {
                return ResourceManager.GetString("FaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string FaultSource {
            get {
                return ResourceManager.GetString("FaultSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StackTrace.
        /// </summary>
        public static string FaultStackTrace {
            get {
                return ResourceManager.GetString("FaultStackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TargetSite.
        /// </summary>
        public static string FaultTargetSite {
            get {
                return ResourceManager.GetString("FaultTargetSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogMessage.
        /// </summary>
        public static string LogMessage {
            get {
                return ResourceManager.GetString("LogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string LogMessageApplicationName {
            get {
                return ResourceManager.GetString("LogMessageApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string LogMessageCategory {
            get {
                return ResourceManager.GetString("LogMessageCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContextData.
        /// </summary>
        public static string LogMessageContextData {
            get {
                return ResourceManager.GetString("LogMessageContextData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EventType.
        /// </summary>
        public static string LogMessageEventType {
            get {
                return ResourceManager.GetString("LogMessageEventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExecutionDetails.
        /// </summary>
        public static string LogMessageExecutionDetails {
            get {
                return ResourceManager.GetString("LogMessageExecutionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string LogMessageId {
            get {
                return ResourceManager.GetString("LogMessageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string LogMessageMessage {
            get {
                return ResourceManager.GetString("LogMessageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaInformation.
        /// </summary>
        public static string LogMessageMetaInformation {
            get {
                return ResourceManager.GetString("LogMessageMetaInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string LogMessagePriority {
            get {
                return ResourceManager.GetString("LogMessagePriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeStamp.
        /// </summary>
        public static string LogMessageTimeStamp {
            get {
                return ResourceManager.GetString("LogMessageTimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER_RESPONSE.
        /// </summary>
        public static string OrderResponse {
            get {
                return ResourceManager.GetString("OrderResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER_RESPONSE_CONTEXT.
        /// </summary>
        public static string OrderResponseContext {
            get {
                return ResourceManager.GetString("OrderResponseContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER_RESPONSE_DATA.
        /// </summary>
        public static string OrderResponseData {
            get {
                return ResourceManager.GetString("OrderResponseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER_STATUS_RESPONSE.
        /// </summary>
        public static string QueryOrderStatusResponse {
            get {
                return ResourceManager.GetString("QueryOrderStatusResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER_STATUS_RESPONSE_DATA.
        /// </summary>
        public static string QueryOrderStatusResponseData {
            get {
                return ResourceManager.GetString("QueryOrderStatusResponseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQUEST.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESPONSE.
        /// </summary>
        public static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESPONSE_CODE.
        /// </summary>
        public static string ResponseCode {
            get {
                return ResourceManager.GetString("ResponseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESPONSE_CONTEXT.
        /// </summary>
        public static string ResponseContext {
            get {
                return ResourceManager.GetString("ResponseContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESPONSE_DATA.
        /// </summary>
        public static string ResponseData {
            get {
                return ResourceManager.GetString("ResponseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYPE.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
    }
}
